stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
  - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  - docker info
  - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
  - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  - docker info
  - docker run -d -p 5000:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
